version: '3.8'
services:
  mysql_usuarios:
    image: mysql:latest
    container_name: mysql-usuarios-container
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: usuarios_db
    volumes:
      - ./docker/mysql/usuarios_db_data:/var/lib/mysql
    networks:
      - ali-network
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  securityservice:
    build:
      context: ./usuariosecurityservice
      dockerfile: Dockerfile
    container_name: security-container
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_usuarios:3306/usuarios_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_SERVER_ADDRESS: 0.0.0.0
      SPRING_SERVER_PORT: 8087
      jpa:
      hibernate:
      ddl-auto: update
      show-sql: true
    depends_on:
      mysql_usuarios:
        condition: service_healthy
    networks:
      - ali-network

  mysql_apiculturapp:
    image: mysql:latest
    container_name: mysql-apiculturapp-container
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: apiculturapp_db
    volumes:
      - ./docker/mysql/apiculturapp_db_data:/var/lib/mysql
    networks:
      - ali-network
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  apiculturappservices:
    build:
      context: ./ApiculturappServices
      dockerfile: Dockerfile
    container_name: apiculturappservices-container
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_apiculturapp:3306/apiculturapp_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_SERVER_ADDRESS: 0.0.0.0
      SPRING_SERVER_PORT: 8083
      jpa:
      hibernate:
      ddl-auto: update
      show-sql: true
    depends_on:
      mysql_apiculturapp:
        condition: service_healthy
    networks:
      - ali-network

volumes:
  usuarios_db_data:
  apiculturapp_db_data:

networks:
  ali-network:
    driver: bridge